### ISSUE TITLE
How to add layers to psd file ?

### ISSUE THREAD

**Issue by thangnd2000** [aspose-imaging/Aspose.Imaging-for-Python-Net#1]

**Comment by ESidenko** [comment]
Hi, @thangnd2000! Sorry for a late answer... :-(
Aspose.Imaging for Python support only simple export images in PSD. It does not have any features for manipulate with PSD layers. But it is possible to create a multipage TIFF image and then export it to PSD. Each page will be exported as a separated layer.

**Comment by thangnd2000** [comment]
Thanks for the answer!
